version: 2

project_name: better-fonts

builds:
  - id: better-fonts
    main: ./cmd/better-fonts
    binary: better-fonts
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  mode: keep-existing

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
